/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/analytics/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Alerts V2 */
        get: operations["analytics_alerts_v2_api_v2_analytics_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analytics/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Comparison V2 */
        get: operations["analytics_comparison_v2_api_v2_analytics_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analytics/health-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Score V2 */
        get: operations["health_score_v2_api_v2_analytics_health_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analytics/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Merchants V2 */
        get: operations["analytics_merchants_v2_api_v2_analytics_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analytics/velocity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Velocity V2 */
        get: operations["analytics_velocity_v2_api_v2_analytics_velocity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/budgets/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Progress V2 */
        get: operations["budget_progress_v2_api_v2_budgets_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capture Followups */
        get: operations["capture_followups_api_v2_capture_followups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/followups/{effect_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Capture Followup */
        post: operations["retry_capture_followup_api_v2_capture_followups__effect_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capture Issues */
        get: operations["capture_issues_api_v2_capture_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/issues/{event_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Capture Issue */
        post: operations["reopen_capture_issue_api_v2_capture_issues__event_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/issues/{event_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Capture Issue */
        post: operations["resolve_capture_issue_api_v2_capture_issues__event_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capture/issues/{event_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Capture Issue */
        post: operations["retry_capture_issue_api_v2_capture_issues__event_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals V2 */
        get: operations["list_goals_v2_api_v2_goals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home Briefing */
        get: operations["home_briefing_api_v2_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant List V2 */
        get: operations["merchant_list_v2_api_v2_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/merchants/{merchant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Profile V2 */
        get: operations["merchant_profile_v2_api_v2_merchants__merchant__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance V2 */
        get: operations["balance_v2_api_v2_overview_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview Merchants V2 */
        get: operations["overview_merchants_v2_api_v2_overview_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview Summary V2 */
        get: operations["overview_summary_v2_api_v2_overview_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview Trend V2 */
        get: operations["overview_trend_v2_api_v2_overview_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview/trend-by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trend By Category V2 */
        get: operations["trend_by_category_v2_api_v2_overview_trend_by_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plan/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming Plan */
        get: operations["upcoming_plan_api_v2_plan_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plan/upcoming/{upcoming_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Planned Charge */
        put: operations["update_planned_charge_api_v2_plan_upcoming__upcoming_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plan/upcoming/{upcoming_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Planned Charge */
        post: operations["dismiss_planned_charge_api_v2_plan_upcoming__upcoming_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/recurring/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recurring Review */
        get: operations["recurring_review_api_v2_recurring_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/recurring/suggestions/{suggestion_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Recurring Review */
        post: operations["resolve_recurring_review_api_v2_recurring_suggestions__suggestion_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/spending/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day Spending */
        get: operations["day_spending_api_v2_spending_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/spending/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending Evidence */
        get: operations["spending_evidence_api_v2_spending_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/spending/month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Month Spending */
        get: operations["month_spending_api_v2_spending_month_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/spending/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending Review */
        get: operations["spending_review_api_v2_spending_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/spending/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week Spending */
        get: operations["week_spending_api_v2_spending_week_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transaction V2 */
        post: operations["create_transaction_v2_api_v2_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction V2 */
        get: operations["get_transaction_v2_api_v2_transactions__tx_id__get"];
        /** Update Transaction V2 */
        put: operations["update_transaction_v2_api_v2_transactions__tx_id__put"];
        post?: never;
        /** Delete Transaction V2 */
        delete: operations["delete_transaction_v2_api_v2_transactions__tx_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/transactions/{tx_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction Provenance */
        get: operations["get_transaction_provenance_api_v2_transactions__tx_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/transactions/{tx_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Transaction V2 */
        post: operations["restore_transaction_v2_api_v2_transactions__tx_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/transactions/{tx_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Transaction V2 */
        post: operations["undo_transaction_v2_api_v2_transactions__tx_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/trips/{trip_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip Summary V2 */
        get: operations["trip_summary_v2_api_v2_trips__trip_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Balance */
        Balance: {
            expenses: components["schemas"]["Money"];
            income: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
        };
        /** BudgetProgress */
        BudgetProgress: {
            budget_amount: components["schemas"]["Money"];
            /** Category */
            category: string | null;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Percent */
            percent: number;
            /**
             * Period
             * @enum {string}
             */
            period: "monthly" | "weekly";
            /** Period End */
            period_end: string;
            /** Period Start */
            period_start: string;
            projected: components["schemas"]["Money"];
            remaining: components["schemas"]["Money"];
            spent: components["schemas"]["Money"];
            /**
             * Status
             * @enum {string}
             */
            status: "over_budget" | "warning" | "on_track";
        };
        /** CaptureFollowup */
        CaptureFollowup: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "trip" | "recurring" | "suggestion" | "notification";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "failed";
            /** Transaction Id */
            transaction_id: number;
            /** Updated At */
            updated_at: string;
        };
        /** CaptureFreshness */
        CaptureFreshness: {
            /** Gmail Connected */
            gmail_connected: boolean;
            /** Gmail Last Checked */
            gmail_last_checked: string | null;
            /** Gmail Needs Reconnection */
            gmail_needs_reconnection: boolean;
        };
        /** CaptureIssue */
        CaptureIssue: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Handled */
            handled: boolean;
            /** Id */
            id: number;
            /** Parser Version */
            parser_version: string;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "failed" | "unrecognized";
            /** Transaction Id */
            transaction_id: number | null;
            /** Updated At */
            updated_at: string;
        };
        /** CaptureResolution */
        CaptureResolution: {
            /** Handled */
            handled: boolean;
            /** Id */
            id: number;
        };
        /** CategoryChange */
        CategoryChange: {
            /** Category */
            category: string;
            change: components["schemas"]["Money"];
        };
        /** CategoryComparison */
        CategoryComparison: {
            /** Category */
            category: string;
            change: components["schemas"]["Money"];
            /** Change Percent */
            change_percent: number | null;
            current: components["schemas"]["Money"];
            previous: components["schemas"]["Money"];
        };
        /** CategoryTrendPoint */
        CategoryTrendPoint: {
            /** Categories */
            categories: {
                [key: string]: components["schemas"]["Money"] | null;
            };
            /** Date */
            date: string;
        };
        /** ConversionProvenance */
        ConversionProvenance: {
            /** Quoted At */
            quoted_at: string | null;
            /** Rate */
            rate: string | null;
            /** Source */
            source: string | null;
            /** Status */
            status: ("native" | "resolved" | "indicative" | "unresolved") | null;
        };
        /** GoalContributionV2 */
        GoalContributionV2: {
            amount: components["schemas"]["Money"];
            /** Contributed Date */
            contributed_date: string | null;
            /** Created At */
            created_at: string;
            /** Goal Id */
            goal_id: number;
            /** Id */
            id: number;
            /** Month */
            month: string;
            /** Note */
            note: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "auto" | "manual";
        };
        /** GoalProgress */
        GoalProgress: {
            /** Contributions */
            contributions: components["schemas"]["GoalContributionV2"][];
            /** Id */
            id: number;
            monthly_rate: components["schemas"]["Money"];
            /** Months To Target */
            months_to_target: number | null;
            /** Name */
            name: string;
            /** On Track */
            on_track: ("on_track" | "ahead" | "behind") | null;
            /** Percent */
            percent: number;
            saved_amount: components["schemas"]["Money"];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "paused";
            target_amount: components["schemas"]["Money"];
            /** Target Date */
            target_date: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthScore */
        HealthScore: {
            /** Components */
            components: {
                [key: string]: components["schemas"]["HealthScoreComponent"];
            };
            /** Grade */
            grade: string | null;
            /** Has Income Data */
            has_income_data: boolean;
            /** Period */
            period: string;
            /** Score */
            score: number | null;
        };
        /** HealthScoreComponent */
        HealthScoreComponent: {
            /** Benchmark */
            benchmark?: number | null;
            /** Description */
            description: string;
            /** Label */
            label: string;
            /** Max */
            max: number;
            /** Score */
            score: number;
            /** Value */
            value: number;
        };
        /** HomeBriefing */
        HomeBriefing: {
            /** Capture Issue Count */
            capture_issue_count: number;
            facts: components["schemas"]["SpendingFacts"];
            /** Followup Issue Count */
            followup_issue_count: number;
            freshness: components["schemas"]["CaptureFreshness"];
            /** Recent */
            recent: components["schemas"]["SpendingEvidenceItem"][];
            /** Upcoming */
            upcoming: components["schemas"]["UpcomingCharge"][];
            upcoming_total: components["schemas"]["Money"];
            /** Upcoming Unknown Count */
            upcoming_unknown_count: number;
        };
        /** MerchantRanking */
        MerchantRanking: {
            /** Merchant */
            merchant: string;
            total: components["schemas"]["Money"];
            /** Visits */
            visits: number;
        };
        /** MerchantSummary */
        MerchantSummary: {
            avg_amount: components["schemas"]["Money"];
            /** Category */
            category: string | null;
            /** First Seen */
            first_seen: string;
            /** Last Seen */
            last_seen: string;
            /** Merchant */
            merchant: string;
            /** Notes */
            notes: string;
            /** Tags */
            tags: string[];
            total: components["schemas"]["Money"];
            /** Transaction Count */
            transaction_count: number;
        };
        /** MerchantTrendMonth */
        MerchantTrendMonth: {
            /** Count */
            count: number;
            /** Month */
            month: string;
            total: components["schemas"]["Money"];
        };
        /** MerchantTrendV2 */
        MerchantTrendV2: {
            current_month: components["schemas"]["Money"];
            /** Merchant */
            merchant: string;
            /** Months */
            months: components["schemas"]["MerchantTrendMonth"][];
            previous_month: components["schemas"]["Money"];
        };
        /** Money */
        Money: {
            /**
             * Currency
             * @default SGD
             * @constant
             */
            currency: "SGD";
            /** Minor Units */
            minor_units: number;
        };
        /** NewMerchant */
        NewMerchant: {
            amount: components["schemas"]["Money"];
            /** Category */
            category: string | null;
            /** First Date */
            first_date: string;
            /** Merchant */
            merchant: string;
        };
        /**
         * OriginalMoney
         * @description The amount in its own currency — unlike Money, not always SGD.
         */
        OriginalMoney: {
            /** Currency */
            currency: string;
            /** Minor Units */
            minor_units: number | null;
        };
        /** OverviewSummary */
        OverviewSummary: {
            /** By Category */
            by_category: {
                [key: string]: components["schemas"]["Money"];
            };
            /** End */
            end: string;
            /** Start */
            start: string;
            total: components["schemas"]["Money"];
        };
        /** PeriodComparison */
        PeriodComparison: {
            change: components["schemas"]["Money"];
            /** Change Percent */
            change_percent: number | null;
            /** Current End */
            current_end: string;
            /** Current Start */
            current_start: string;
            current_total: components["schemas"]["Money"];
            /** Previous End */
            previous_end: string;
            /** Previous Start */
            previous_start: string;
            previous_total: components["schemas"]["Money"];
        };
        /** PlanMutationResponse */
        PlanMutationResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** PlannedCharge */
        PlannedCharge: {
            amount: components["schemas"]["Money"] | null;
            /**
             * Confirmation Source
             * @enum {string}
             */
            confirmation_source: "unknown" | "user" | "recurring_suggestion";
            /** Date */
            date: string;
            /** Frequency */
            frequency: string;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * Schedule Status
             * @enum {string}
             */
            schedule_status: "active" | "possibly_cancelled";
            /** Subscription Id */
            subscription_id: number;
        };
        /** QueuedResponse */
        QueuedResponse: {
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** RecurringResolution */
        RecurringResolution: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Subscription Id */
            subscription_id: number | null;
        };
        /** RecurringReview */
        RecurringReview: {
            /** Items */
            items: components["schemas"]["RecurringReviewItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** RecurringReviewItem */
        RecurringReviewItem: {
            /** Frequency */
            frequency: string;
            /** Id */
            id: string;
            /** Merchant */
            merchant: string;
        };
        /** RefundEvidence */
        RefundEvidence: {
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Merchant */
            merchant: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Transaction Id */
            transaction_id: number;
            /** Warning */
            warning?: string | null;
        };
        /** SpendingAlerts */
        SpendingAlerts: {
            /** Anomalies */
            anomalies: components["schemas"]["SpendingAnomaly"][];
            /** New Merchants */
            new_merchants: components["schemas"]["NewMerchant"][];
        };
        /** SpendingAnomaly */
        SpendingAnomaly: {
            amount: components["schemas"]["Money"];
            avg_amount: components["schemas"]["Money"];
            /** Category */
            category: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Id */
            id: number;
            /** Merchant */
            merchant: string | null;
            /** Transaction Date */
            transaction_date: string;
        };
        /** SpendingComparison */
        SpendingComparison: {
            /** Categories */
            categories: components["schemas"]["CategoryComparison"][];
            overall: components["schemas"]["PeriodComparison"];
        };
        /** SpendingEvidence */
        SpendingEvidence: {
            /** Items */
            items: components["schemas"]["SpendingEvidenceItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** SpendingEvidenceItem */
        SpendingEvidenceItem: {
            amount: components["schemas"]["Money"] | null;
            /** Category */
            category: string;
            /**
             * Conversion Status
             * @enum {string}
             */
            conversion_status: "native" | "indicative" | "unresolved";
            /** Date */
            date: string | null;
            /** Id */
            id: number;
            /** Merchant */
            merchant: string | null;
            /** Type */
            type: string;
        };
        /** SpendingFacts */
        SpendingFacts: {
            /** As Of */
            as_of: string;
            /** Category Changes */
            category_changes: components["schemas"]["CategoryChange"][];
            change: components["schemas"]["Money"] | null;
            comparison_current: components["schemas"]["SpendingPeriod"];
            current: components["schemas"]["SpendingPeriod"];
            /**
             * Money Basis
             * @constant
             */
            money_basis: "canonical_minor_units_with_legacy_fallback";
            previous: components["schemas"]["SpendingPeriod"];
            /** Timezone */
            timezone: string;
            /** Undated Count */
            undated_count: number;
        };
        /** SpendingPeriod */
        SpendingPeriod: {
            /** End */
            end: string;
            income: components["schemas"]["Money"] | null;
            /** Indicative Count */
            indicative_count: number;
            recorded_net_flow: components["schemas"]["Money"] | null;
            spending: components["schemas"]["Money"];
            /** Start */
            start: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "indicative" | "partial";
            /** Transaction Count */
            transaction_count: number;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /** SpendingReview */
        SpendingReview: {
            /** Items */
            items: components["schemas"]["SpendingReviewItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** SpendingReviewItem */
        SpendingReviewItem: {
            /** Category */
            category: string;
            /** Date */
            date: string | null;
            /** Id */
            id: number;
            /** Merchant */
            merchant: string | null;
            /** Reasons */
            reasons: ("missing_date" | "unresolved_money" | "unknown_type" | "missing_merchant" | "missing_category")[];
        };
        /** SpendingVelocity */
        SpendingVelocity: {
            current_mtd: components["schemas"]["Money"];
            /** Days Elapsed */
            days_elapsed: number;
            last_month_total: components["schemas"]["Money"];
            /** Pace Percent */
            pace_percent: number;
            projected_total: components["schemas"]["Money"];
            /**
             * Status
             * @enum {string}
             */
            status: "ahead" | "on_track" | "behind";
            /** Total Days */
            total_days: number;
        };
        /** TopMerchant */
        TopMerchant: {
            avg_amount: components["schemas"]["Money"];
            /** Count */
            count: number;
            /** Merchant */
            merchant: string;
            total: components["schemas"]["Money"];
        };
        /** TopMerchantsResult */
        TopMerchantsResult: {
            /** Top */
            top: components["schemas"]["TopMerchant"][];
            trend: components["schemas"]["MerchantTrendV2"] | null;
        };
        /**
         * TransactionCorrection
         * @description PUT /api/v2/transactions/{id} body. All fields optional — only
         *     supplied ones are changed. expected_revision is optional so existing
         *     v1-style callers (that never read a revision back) still work.
         */
        TransactionCorrection: {
            /** Amount */
            amount?: number | null;
            /** Category */
            category?: string | null;
            /** Currency */
            currency?: string | null;
            /** Description */
            description?: string | null;
            /** Exchange Rate */
            exchange_rate?: number | null;
            /** Expected Revision */
            expected_revision?: number | null;
            /** Merchant */
            merchant?: string | null;
            /** Refund Of Transaction Id */
            refund_of_transaction_id?: number | null;
            /**
             * Remember Category
             * @default false
             */
            remember_category: boolean;
            /** Transaction Date */
            transaction_date?: string | null;
            /** Type */
            type?: string | null;
        };
        /**
         * TransactionCreate
         * @description POST /api/v2/transactions body.
         */
        TransactionCreate: {
            /** Amount */
            amount: number;
            /** Category */
            category?: string | null;
            /**
             * Currency
             * @default SGD
             */
            currency: string;
            /** Description */
            description?: string | null;
            /** Exchange Rate */
            exchange_rate?: number | null;
            /** Merchant */
            merchant?: string | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "cash";
            /** Transaction Date */
            transaction_date?: string | null;
            /**
             * Type
             * @default expense
             * @enum {string}
             */
            type: "expense" | "income";
        };
        /**
         * TransactionDeletion
         * @description DELETE /api/v2/transactions/{id} response — the retained snapshot,
         *     as it stood immediately before deletion.
         */
        TransactionDeletion: {
            /** Category */
            category: string | null;
            conversion: components["schemas"]["ConversionProvenance"];
            /** Deleted At */
            deleted_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Merchant */
            merchant: string | null;
            original: components["schemas"]["OriginalMoney"];
            refund_of?: components["schemas"]["RefundEvidence"] | null;
            /**
             * Refunded By
             * @default []
             */
            refunded_by: components["schemas"]["RefundEvidence"][];
            reporting: components["schemas"]["Money"] | null;
            /** Revision */
            revision: number;
            /** Source */
            source: string;
            /** Transaction Date */
            transaction_date: string | null;
            /** Type */
            type: string;
        };
        /** TransactionProvenance */
        TransactionProvenance: {
            /** Sources */
            sources: components["schemas"]["TransactionSource"][];
            /** Transaction Id */
            transaction_id: number;
        };
        /** TransactionSource */
        TransactionSource: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "apple_wallet" | "gmail" | "manual" | "cash" | "other";
            /** Evidence Recorded */
            evidence_recorded: boolean;
        };
        /**
         * TransactionUndo
         * @description POST /api/v2/transactions/{id}/undo body. expected_revision is
         *     optional — omitted, undo always reverts whatever correction most
         *     recently happened.
         */
        TransactionUndo: {
            /** Expected Revision */
            expected_revision?: number | null;
        };
        /** TransactionV2 */
        TransactionV2: {
            /** Category */
            category: string | null;
            conversion: components["schemas"]["ConversionProvenance"];
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Merchant */
            merchant: string | null;
            original: components["schemas"]["OriginalMoney"];
            refund_of?: components["schemas"]["RefundEvidence"] | null;
            /**
             * Refunded By
             * @default []
             */
            refunded_by: components["schemas"]["RefundEvidence"][];
            reporting: components["schemas"]["Money"] | null;
            /** Revision */
            revision: number;
            /** Source */
            source: string;
            /** Transaction Date */
            transaction_date: string | null;
            /** Type */
            type: string;
        };
        /** TrendPoint */
        TrendPoint: {
            amount: components["schemas"]["Money"];
            /** Date */
            date: string;
        };
        /** TripCategoryTotal */
        TripCategoryTotal: {
            amount: components["schemas"]["Money"];
            /** Category */
            category: string;
            /** Count */
            count: number;
        };
        /** TripDayTotal */
        TripDayTotal: {
            amount: components["schemas"]["Money"];
            /** Date */
            date: string;
        };
        /** TripInfo */
        TripInfo: {
            /** Created At */
            created_at: string;
            /** Destination */
            destination: string | null;
            /** End Date */
            end_date: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Primary Currency */
            primary_currency: string;
            /** Start Date */
            start_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "inactive" | "active";
            /** Updated At */
            updated_at: string;
        };
        /** TripSummary */
        TripSummary: {
            /** By Category */
            by_category: components["schemas"]["TripCategoryTotal"][];
            /** By Day */
            by_day: components["schemas"]["TripDayTotal"][];
            /** Currencies Used */
            currencies_used: string[];
            daily_average: components["schemas"]["Money"];
            /** Days */
            days: number;
            total: components["schemas"]["Money"];
            /** Transaction Count */
            transaction_count: number;
            trip: components["schemas"]["TripInfo"];
        };
        /** UpcomingCharge */
        UpcomingCharge: {
            amount: components["schemas"]["Money"] | null;
            /** Date */
            date: string;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Subscription Id */
            subscription_id: number;
        };
        /** UpcomingPlan */
        UpcomingPlan: {
            /** Enabled */
            enabled: boolean;
            /** End */
            end: string;
            /** Items */
            items: components["schemas"]["PlannedCharge"][];
            known_total: components["schemas"]["Money"];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Start */
            start: string;
            /**
             * Status
             * @enum {string}
             */
            status: "partial" | "estimated";
            /** Timezone */
            timezone: string;
            /** Total */
            total: number;
            /** Unknown Count */
            unknown_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analytics_alerts_v2_api_v2_analytics_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingAlerts"];
                };
            };
        };
    };
    analytics_comparison_v2_api_v2_analytics_comparison_get: {
        parameters: {
            query?: {
                period?: string;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_score_v2_api_v2_analytics_health_score_get: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_merchants_v2_api_v2_analytics_merchants_get: {
        parameters: {
            query?: {
                limit?: number;
                merchant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMerchantsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_velocity_v2_api_v2_analytics_velocity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingVelocity"];
                };
            };
        };
    };
    budget_progress_v2_api_v2_budgets_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetProgress"][];
                };
            };
        };
    };
    capture_followups_api_v2_capture_followups_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureFollowup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_capture_followup_api_v2_capture_followups__effect_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                effect_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_issues_api_v2_capture_issues_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                include_handled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureIssue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_capture_issue_api_v2_capture_issues__event_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_capture_issue_api_v2_capture_issues__event_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_capture_issue_api_v2_capture_issues__event_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_v2_api_v2_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalProgress"][];
                };
            };
        };
    };
    home_briefing_api_v2_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeBriefing"];
                };
            };
        };
    };
    merchant_list_v2_api_v2_merchants_get: {
        parameters: {
            query?: {
                sort_by?: string;
                tag?: string | null;
                category?: string | null;
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_profile_v2_api_v2_merchants__merchant__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    balance_v2_api_v2_overview_balance_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_merchants_v2_api_v2_overview_merchants_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantRanking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_summary_v2_api_v2_overview_summary_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_trend_v2_api_v2_overview_trend_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trend_by_category_v2_api_v2_overview_trend_by_category_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_plan_api_v2_plan_upcoming_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_planned_charge_api_v2_plan_upcoming__upcoming_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upcoming_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_planned_charge_api_v2_plan_upcoming__upcoming_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upcoming_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_review_api_v2_recurring_review_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_recurring_review_api_v2_recurring_suggestions__suggestion_id___action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
                action: "accept" | "dismiss";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    day_spending_api_v2_spending_day_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingFacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spending_evidence_api_v2_spending_evidence_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                category?: string | null;
                measure?: "spending" | "income" | "unresolved";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingEvidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    month_spending_api_v2_spending_month_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingFacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spending_review_api_v2_spending_review_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_spending_api_v2_spending_week_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingFacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_v2_api_v2_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_v2_api_v2_transactions__tx_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_v2_api_v2_transactions__tx_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_v2_api_v2_transactions__tx_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDeletion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_provenance_api_v2_transactions__tx_id__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionProvenance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_transaction_v2_api_v2_transactions__tx_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_transaction_v2_api_v2_transactions__tx_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransactionUndo"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_summary_v2_api_v2_trips__trip_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
